version: "3.7"

networks:
  news:

services:
  front:
    build:
      context: ./front
      dockerfile: ./docker/front/Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true    

  rssparser:
    environment:
      - PG_URL=postgres://postgres:postgres@postgres/db_news?sslmode=disable
      - LOG_LEVEL=debug
      - PG_MIGRATIONS_PATH=file://../../migrations
    build:
      context: .
      dockerfile: ./docker/rssparser/Dockerfile
    depends_on:
      - postgres
    networks:
      - news

  apiserver:
    restart: always
    environment:
      - HTTP_ADDR=:1324
      - PG_URL=postgres://postgres:postgres@postgres/db_news?sslmode=disable
      - LOG_LEVEL=debug
      - PG_MIGRATIONS_PATH=file://../../migrations
    build:
      context: .
      dockerfile: ./docker/apiserver/Dockerfile
    ports:
      - 1324:1324
    depends_on:
      - postgres
    networks:
      - news

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=db_news
    ports:
      - 5432:5432
    networks:
      - news

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - news
