version: "3.7"

services:
  server:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: ./server/Dockerfile
    ports:
      - "8081:8081"
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - database.env
    networks:
    - postgresql

  parser:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: ./parser/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    env_file:
      - database.env
    networks:
      - postgresql

  postgres:
    image: postgres
    volumes:
     - /var/postgresql/data:/var/lib/postgresql/data
    env_file:
     - database.env
    networks:
     - postgresql

  pgadmin4:
    image: thajeztah/pgadmin4
    ports:
     - "5050:5050"
    depends_on:
     - postgres
    networks:
     - postgresql

networks:
  postgresql:
        driver: bridge
