version: "3.7"

services:
  server:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: ./server/Dockerfile
    ports:
      - "8080:8081" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: unless-stopped
    depends_on:
      - postgres
    environment: # Pass environment variables to the service
      DATABASE_URL: "host=localhost port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB} password=${POSTGRES_PASSWORD}"
    env_file:
      - .env

  parser:
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: ./parser/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres
    environment: # Pass environment variables to the service
      DATABASE_URL: "host=localhost port=5432 user=${POSTGRES_USER} dbname=${POSTGRES_DB} password=${POSTGRES_PASSWORD}"
    env_file:
      - .env

  postgres:
    image: postgres
    restart: always
    volumes:
     - /var/postgresql/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
     - postgresql

  pgadmin4:
    image: dpage/pgadmin4
    restart: always
    ports:
     - "8228:80"
    depends_on:
     - postgres
    env_file:
      - .env
    networks:
     - postgresql

networks:
  postgresql:
        driver: bridge
